# Generated by Django 4.0.6 on 2022-07-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_catergory_product_price_product_subcateogry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='MAC/meida/shop/images'),
        ),
    ]
